### ISSUE TITLE
ERR: muxer error: unable to extract DTS: invalid POC

### ISSUE THREAD

**Issue by andrew-ld** [bluenviron/mediamtx#1552]
## Which version are you using?

https://github.com/aler9/rtsp-simple-server/commit/25dc252342b44971a731d8795cb3536213f8d797

## Which operating system are you using?

https://github.com/andrew-ld/rtsp-simple-server/blob/e24eaba1ffc80e1e8ee297fab2f55e4747ef0882/Dockerfile

## Describe the issue

When retransmitting an rtsp stream from ffmpeg to rtsp-simple-server using runOnInit about every minute I get an error from the hls muxer (hlsAlwaysRemux is active).

the affected log lines are these

```
2023/03/10 08:58:08 WAR [RTSP] [session dfc6ecdc] 2 RTP packet(s) lost

2023/03/10 08:58:08 INF [HLS] [muxer vdeo_52089] ERR: muxer error: unable to extract DTS: invalid POC
```

often when the muxer gives this problem a few moments earlier rtsp complains about packet loss

**I use these options with ffmpeg:**

```
ffmpeg -rtsp_transport tcp -i $[RTSP_UPSTREAM_URL} \
 -c copy \
 -f segment -segment_time 00:30:00 -reset_timestamps 1 -strftime 1 \
 /${STORAGE}/output#%Y-%m-%d_%H-%M-%S-%z#${DEVICE_ID}.ts \
 -c:v copy -c:a libopus -b:a 16k \
 -f rtsp rtsp://ffmpeg:${PUBLISH_SECRET}@localhost:${RTSP_PORT}/${RTSP_PATH}
```

the same stream by connecting it directly to rtsp-simple-server does not give this problem, it seems that only retransmitting it gives this problem.

I have tried adding various hacks to ffmpeg such as
- use_wallclock_as_timestamps
- map 0:0
- fflags +igndts+genpts

**Comment by aler9** [comment]
Hello,

In order to record incoming streams, my advice is to use FFmpeg inside `runOnReady` as described here:
https://github.com/aler9/rtsp-simple-server#save-streams-to-disk

Eventually the recording feature will be integrated into the server as described here #1399

The issue with using HLS to record streams is that most HLS client expects a clean playlist, without gaps in time and without errors, and that's the reason why segments and playlists are resetted in case of error.

Anyway, if you post a sample recording of the stream that causes the error, we can try to fix the error instead of adding workarounds. You can record the stream by using

```
ffmpeg -i rtsp://original-stream -t 00:02:00 -c copy -f mpegts record.ts
```

**Comment by yanhua1012** [comment]
I have encounter the same situation.
the version of mediamtx.exe is 0.23.6
below is the record file link from rom video source
[https://drive.google.com/file/d/1HvqLgkKf-c19jcjn5CZ9MfZ3UW8ICcMn/view?usp=sharing](url)

below is the link of mediamtx.yml
[https://drive.google.com/file/d/1EfKak99D6pcRjKc5_L3HmeYBU7roZyvy/view?usp=sharing](url)

**Comment by aler9** [comment]
This error has been removed by https://github.com/bluenviron/mediacommon/pull/55, timing-related issues are still possible and are tracked in https://github.com/bluenviron/mediamtx/issues/1002.
