### ISSUE TITLE
publishing RTSP stream and using hls lowLatency or fmp4 does not create init.mp4. returns 404 NOT FOUND

### ISSUE THREAD

**Issue by johnvoipguy** [bluenviron/mediamtx#1706]
## Which version are you using?

v0.22.0
## Which operating system are you using?

5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Publishing RTSP stream and using hls lowLatency or fmp4 does not create init.mp4 file. works fine with mpegts as the hls format.
When I choose hls lowLatency or fmp4 the client receives an 404 not found for the init.mp4 file. the index.m3u8 and stream.m3u8 return 200 ok. 

## Describe how to replicate the issue

1. start mediamtx
2. publish with with ffmmpeg  -loglevel info -stats -fflags +discardcorrupt+nobuffer  -rtsp_transport udp+tcp -max_delay 0 -rtsp_flags prefer_tcp -reorder_queue_size 15 -allowed_media_types video -i 'rtsp://127.0.0.1:8554/Frontyard'  -rtsp_transport +udp+tcp -max_delay 0 -rtsp_flags prefer_tcp -f rtsp -muxdelay 0 'rtsp://127.0.0.1:8554/xstack' 
3. any ol' browser to http://x.x.x.x:8888/xstack/

## Did you attach the server logs?

yes

## Did you attach a network dump?
no

[mediamtx.log](https://github.com/aler9/mediamtx/files/11228469/mediamtx.log)
 no
it's the same box. using the loopback IP.

**Comment by timerlan** [comment]
Similar problem. 404 for the init.mp4 in fmp4 mode
https://github.com/aler9/mediamtx/issues/1696

**Comment by aler9** [comment]
@johnvoipguy @timerlan i've updated the server in order to print an error in case init.mp4 can't be generated. Please test this nightly release and let me know whether it prints errors. Thanks

[mediamtx_v0.22.1_darwin_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11236620/mediamtx_v0.22.1_darwin_amd64.tar.gz)
[mediamtx_v0.22.1_linux_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11236621/mediamtx_v0.22.1_linux_amd64.tar.gz)
[mediamtx_v0.22.1_linux_arm64v8.tar.gz](https://github.com/aler9/mediamtx/files/11236623/mediamtx_v0.22.1_linux_arm64v8.tar.gz)
[mediamtx_v0.22.1_linux_armv6.tar.gz](https://github.com/aler9/mediamtx/files/11236628/mediamtx_v0.22.1_linux_armv6.tar.gz)
[mediamtx_v0.22.1_linux_armv7.tar.gz](https://github.com/aler9/mediamtx/files/11236629/mediamtx_v0.22.1_linux_armv7.tar.gz)
[mediamtx_v0.22.1_windows_amd64.zip](https://github.com/aler9/mediamtx/files/11236630/mediamtx_v0.22.1_windows_amd64.zip)

**Comment by timerlan** [comment]
Now the behavior has changed. The browser is make a request to file: index.m3u8

Server log: [log.txt](https://github.com/aler9/mediamtx/files/11240391/log.txt)

![image](https://user-images.githubusercontent.com/13770939/232248183-b97333a4-b4ec-430b-8f82-1381dd0d2363.png)

If open index.m3u8 link in VLC video freezes after 2-4 seconds.

**Comment by aler9** [comment]
@timerlan check if your browser is able to play H265, from what i know only Windows Chrome on a pc with a compatible GPU can. Click here:

https://jsfiddle.net/4msrhudv

**Comment by johnvoipguy** [comment]
it isn't doing now after using the latest build  you sent.... However for completeness, here are the logs for hls/fmp with remux_always=no and yes.
[mediamtx_fmp4_remux_no.log](https://github.com/aler9/mediamtx/files/11241402/mediamtx_fmp4_remux_no.log)
[mediamtx_fmp4_remux_yes.log](https://github.com/aler9/mediamtx/files/11241403/mediamtx_fmp4_remux_yes.log)
[mediamtx_llhls_remux_no.log](https://github.com/aler9/mediamtx/files/11241404/mediamtx_llhls_remux_no.log)
[mediamtx_llhls_remux_yes.log](https://github.com/aler9/mediamtx/files/11241405/mediamtx_llhls_remux_yes.log)

**Comment by aler9** [comment]
@johnvoipguy can you confirm me that the changes included in the nightly release are able to solve the issue?

**Comment by johnvoipguy** [comment]
Based on the current testing, the issues have been resolved.

**Comment by timerlan** [comment]
> 

Problem solved
