### ISSUE TITLE
gestreamer a=rtpmap:96 MP4A-LATM/48000 invalid clock

### ISSUE THREAD

**Issue by wbtcpip2** [bluenviron/mediamtx#1716]
## Which version are you using?

v0.22.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

when streaming rtsp with gstreamer as soruce i get error "invalid SDP: media 1 is invalid: invalid clock: 48000"

## Describe how to replicate the issue

1. start the server

2. publish with gstreamer with following pipeline:
gst-launch-1.0.exe -e videotestsrc ! mfh264enc bitrate=1024 ! video/x-h264 ! rtspclientsink name=mux location=rtsp://:8554/live audiotestsrc ! audioconvert ! audioresample ! audio/x-raw, rate=48000 ! mfaacenc bitrate=128000 ! audio/mpeg ! mux.

3. mediamtx log show
2023/04/17 12:25:11 INF [RTSP] [conn [fe80::c6c4:6666:5c9c:2af5%vEthernet (Ethernet 2)]:65064] closed (invalid SDP: media 1 is invalid: invalid clock: 48000)

## Did you attach the server logs?
yes
[mediamtx.log](https://github.com/aler9/mediamtx/files/11249057/mediamtx.log)

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Thanks for reporting the issue, it has been fixed. Since a new server version won't be published for a while, you can use this nightly release.
[mediamtx_v0.22.2_darwin_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11253163/mediamtx_v0.22.2_darwin_amd64.tar.gz)
[mediamtx_v0.22.2_linux_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11253165/mediamtx_v0.22.2_linux_amd64.tar.gz)
[mediamtx_v0.22.2_linux_arm64v8.tar.gz](https://github.com/aler9/mediamtx/files/11253168/mediamtx_v0.22.2_linux_arm64v8.tar.gz)
[mediamtx_v0.22.2_linux_armv6.tar.gz](https://github.com/aler9/mediamtx/files/11253169/mediamtx_v0.22.2_linux_armv6.tar.gz)
[mediamtx_v0.22.2_linux_armv7.tar.gz](https://github.com/aler9/mediamtx/files/11253170/mediamtx_v0.22.2_linux_armv7.tar.gz)
[mediamtx_v0.22.2_windows_amd64.zip](https://github.com/aler9/mediamtx/files/11253171/mediamtx_v0.22.2_windows_amd64.zip)

**Comment by aler9** [comment]
fixed in v0.23.0
