### ISSUE TITLE
OBS(RTMP) -> HLS -> Chrome works, Firefox not.

### ISSUE THREAD

**Issue by hagbrain21** [bluenviron/mediamtx#1938]
## Which version are you using?

v0.23.5

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Stream RTMP OBS -> mediametx -> HLS -> Client. Stream works in Chrome without problems. In Firefox there is no Stream and this Error occurs when starting the stream (opening the URL):

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://cdn.jsdelivr.net/npm/hls.js@1.4.3
Source-Map-Adresse: hls.min.js.map

and then every second this appears:

Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.

Also every second the posted block from the server log appears.

I found something about the only once appearing warning (I dont know how to code but maybe it helps?):
https://github.com/video-dev/hls.js/issues/1671 (at bottom)
Let me know if you need more information etc. Thank you for this great project!

## Describe how to replicate the issue

1. start the server
2. OBS RTMP Stream (CBR,30000Kbps,KeyFrame0,default) to server with standard settings on server.
3. Open URL of server with Chrome works.
4. Open same URL with Firefox, Errors appear.

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

[relevantlog.txt](https://github.com/bluenviron/mediamtx/files/11714012/relevantlog.txt)

**Comment by zapf2000** [comment]
Which codec did you use? H264/AAC?

**Comment by hagbrain21** [comment]
H264

**Comment by aler9** [comment]
Hello, exception "The fetching process for the media resource was aborted by the user agent at the user's request" usually means that Firefox doesn't support the video or audio codec of the stream. It may be a server issue (very remotely), in order to find it out you can:

1. start the server with option `logLevel: debug`
2. publish the video stream from OBS to the server
3. read the stream with VLC and RTSP for 10 seconds
4. attach log

In this way, logs will contain the codec name and parameters, and we will be able to check whether Firefox supports them or not.

**Comment by aler9** [comment]
closed since no additional feedback was provided.
