### ISSUE TITLE
Control WEBRTC

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2017]
## Describe the feature

I open a webrtc stream in an ios/android application in a webview and it's not very convenient and correct to render controls, so I ask you to add(or add the ability to connect to the stream via wss) a parameter to the configuration file to disable control on the webrtc page as shown below:

```yaml
# Enable Controls on the WebRTC page.
webrtcControls: yes
```

i change string 22 in file webrtc_read_index.html
it was like this: `<video id="video" muted controls autoplay playsinline></video>`

became like this: `<video id="video" muted autoplay playsinline></video>`

**Comment by aler9** [comment]
Hello, i can't disable controls since 

* they allow to un-mute the audio, and the audio has to be started muted otherwise autoplay doesn't work
* since autoplay is disabled when low-power mode of iPhones and Android smartphones is turned on, controls allow to start the stream

If you need to disable them for your specific case in which you don't care about audio or low power mode, either create a custom web page or use an i-frame with the `pointer-events` CSS property set to none:

```
<iframe style="pointer-events: none;" src="http://mediamtx:8889/mystream"></iframe>
```

**Comment by pikachu937** [comment]
I initially understood that you cannot disable controls by default, so I suggested doing it through a flag (variable).

**Comment by daleffe** [comment]
> I initially understood that you cannot disable controls by default, so I suggested doing it through a flag (variable).

Hello @pikachu937 I've been reading the [file that generates WebRTC streaming page](https://github.com/bluenviron/mediamtx/blob/5dae270900517b73473dd6fc5d68fe19faab91ad/internal/core/webrtc_read_index.html#L369C4-L369C4) and we've the option to pass the following boolean query string parameters:

- **controls**
- **muted**
- **autoplay**
- **playsInLine**

So, in addition to disabling mouse events described above by @aler9 , we can pass the iframe source URL as follows:
`<iframe src="http://mediamtx:8889/mystream?controls=false"></iframe>`
