### ISSUE TITLE
Webrts wss

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2095]
## Describe the feature

By default, mobile platforms work better with webrtc over **wss** (it's not for nothing that all voip platforms use ws or wss). To connect your version of webrtc, you have to use a workaround (crutch) solution like webview, which of course has a place to be, but it’s still more correct to do exactly wss and connect a ready-made link in the built-in player. Most libraries for ios/andtoid prefer to use wss.

**Comment by aler9** [comment]
Hello, what do you mean by "mobile platforms works better with WebRTC over WebSocket?" Does it involve a performance improvement? Can you provide some data?

**Comment by pikachu937** [comment]
I mean that most libraries for programming under ios/android ask for a link in the form of wss://domain.com:8889/stream, which is initially more correct than embedding an element of the webview type in the application and rendering the html page.

**Comment by aler9** [comment]
WebRTC over WebSocket is not standardized and can be implemented in multiple ways (i.e. by including ICE servers or not), there's no way to tell which one is right, so even if we want to, this feature can't be implemented unless by targeting a specific library.

On the contrary, WHEP and WHIP are standardized and are already supported by a lot of software. Find a library that supports WHEP and WHIP or contact the authors of your library in order to add support for them.

**Comment by pikachu937** [comment]
The fact of the matter is that there are no libraries with native whep/whip support in ios/android. Your implementation of webrtc can only be viewed through a web browser, and therefore, when writing an application, only webview can display video.
