### ISSUE TITLE
Allowing record to certain paths doesn't work well.

### ISSUE THREAD

**Issue by RaceDriverMIKU** [bluenviron/mediamtx#2423]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Set to allow recording streams to disk, and doing like below doesn't let me record well. it barely allow me recording streams. it only does record sometimes.
Software I tested was OBS, Larix Broadcaster.
Path:
  ~^prefix:
     record: yes

  all:
    record: no
![image](https://github.com/bluenviron/mediamtx/assets/12777127/a84552ac-dd48-499a-9b89-ab06083c8fb8)
![image](https://github.com/bluenviron/mediamtx/assets/12777127/5435eccc-7206-4a39-8c53-2bd18c2085e0)

## Describe how to replicate the issue

1. enable global record.(line 245)
2. disable record of path "all"
3. make any paths, and allow it record streams.(my case, ~^record)

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, from the logs you posted, this has nothing to do with recording, it's the SRT connection that gets closed every few seconds by the publisher, which is surely not one of the two you wrote, since Larix doesn't support SRT, while OBS with SRT works without any problem.
If you still have problems, reopen the issue and provide detailed instructions on how to replicate.
