### ISSUE TITLE
RTSP proxy losing frames on ARM64 starting with 0.20.1

### ISSUE THREAD

**Issue by iXPert12** [bluenviron/mediamtx#2463]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

I have several older Sercomm cameras, which i proxied for over a year successfully. After migrating my raspberry pi 4 to ARM64( DietPi 8.22, Debian Bookworm), I noticed some lagging in the proxied stream, which didn't happen before. After several days of investigation the results are: 
* every 15-20 seconds the stream is losing approximately 50 frames
* the issue occurs only on ARM64 and only starting with 0.20.1 (older versions <0.20.1 works ok, tested several versions of 0.19, and 0.20.0).
* on ARMv7 and on MacOS AMD64 the latest version 1.1.1 works fine. 

## Did you attach the server logs?

yes

## Did you attach a network dump?

 no
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/12819074/mediamtx.log)

![Screenshot 2023-10-05 at 16 35 12](https://github.com/bluenviron/mediamtx/assets/2253764/5b9f5247-9b05-4aa8-a1d4-19a7ca9b3bcf)

![Screenshot 2023-10-05 at 16 34 47](https://github.com/bluenviron/mediamtx/assets/2253764/17715d11-2ef7-4fba-83ec-c87ada221357)

**Comment by aler9** [comment]
Hello, the main differences between v0.20.1 and v0.20.0 are

* Golang was updated from Go 1.17 to go 1.18
* gortsplib was updated from 27f8015ac619 to 7d8e3cf5bc03 - the difference is that RTCP sender reports are sent even when the transport protocol is TCP (https://github.com/bluenviron/gortsplib/compare/27f8015ac619...7d8e3cf5bc03)

Maybe the Golang update caused the issue, since Golang is the only platform-specific component involved.

Anyway, it's not clear where the bug lies, since it may lie in data transfer between server and VLC, or it may lie in video decoding inside VLC. Since VLC reports lost frames, it is probably able to detect which errors are causing the loss of frames. If you launch VLC with the `-vvv` option, you can get the error log.

**Comment by aler9** [comment]
closed since no additional informations were provided.
