### ISSUE TITLE
Version shows v0.0.0

### ISSUE THREAD

**Issue by mvoh** [bluenviron/mediamtx#2489]
## Which version are you using?

v1.1.1  
*but how to find out???* :)

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (please describe)
```
$ uname -a
OpenBSD xxxxxxx 7.3 GENERIC.MP#3 amd64
```

## Describe the issue

[internal/core/core.go#L27](https://github.com/bluenviron/mediamtx/blob/9de64238a5dc7775560ce5b1b4c4d4470ffa6186/internal/core/core.go#L27)
`var version = "v0.0.0"`

## Describe how to replicate the issue
```
git clone https://github.com/bluenviron/mediamtx.git
cd mediamtx/
go build .
```
```
$ mediamtx --version
v0.0.0
```
```
$ mediamtx -h
MediaMTX v0.0.0
```

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, version is currently filled manually by using

```
go build -ldflags "-X github.com/bluenviron/mediamtx/internal/core.version=vX.X.X"
```

This is the same approach used by most Golang-based command line utilities like Helm, Kubectl and Skaffold.

The alternatives are:

* Filling version statically by performing a dedicated commit before every release. This has the disadvantage of introducing an additional task during release, furthermore it doesn't allow to detect custom releases since their version would be the same as standard releases
* Using a new Golang feature that automatically provides the git revision through [BuildInfo](https://pkg.go.dev/debug/buildinfo), the problem of this is that it's causing troubles in CI/CD systems that strip the .git folder or don't have git installed, and when the executable is installed with `go install`, furthermore this feature doesn't provide the git tag, but only the alphanumeric revision.

Currently these alternatives cannot be taken into consideration for the reasons explained above.
