### ISSUE TITLE
Feature Request : HTTP MPEG-TS & SRT custom port caller and custom port Play

### ISSUE THREAD

**Issue by cmigb** [bluenviron/mediamtx#2510]
## Describe the feature

 **HTTP MPEGTS  SRT custom port caller and custom port Play**

I appreciate the recent updates I have a couple of feature requests in mind

1 HTTP MPEGTS Playback It would be fantastic if you could introduce the capability to play HTTP MPEGTS streams This feature would enhance the versatility of the system
http://localhost/streamname.ts or something. I hope mpeg2/h262 supported

2 SRT Publishing Without Stream Name It would be convenient if we could publish SRT streams without specifying a stream name just by using the format srt://ip:port Additionally it would be great if we could define custom ports for SRT playback for example srt://ip:customport These enhancements would make working with SRT more flexible
To add a section for predefined SRT streams with custom ports for publishing and playing in a mediamtx.yaml configuration file you can modify the YAML file as follows

Add a section for SRT configuration in existing mediamtx.yaml 

srtstreams 
   name SRT Stream 1
    publishurl srt://localhost:2001
    playurl srt://localhost:3001

   name SRT Stream 2
    publishurl srt://localhost:2002
    playurl srt://localhost:3002

 Existing configuration 

Each stream is defined with a name a descriptive name for the stream publish url the SRT URL for publishing and read/play url the SRT URL for playing

Thank you for considering these suggestions

**Comment by aler9** [comment]
Hello,

First of all, instructions say

> Please create a request FOR EACH feature. Do not report multiple features in a single request, otherwise they'll probably never get ALL implemented.

Regarding the two features you're suggesting:

> 1 HTTP MPEGTS Playback It would be fantastic if you could introduce the capability to play HTTP MPEGTS streams This feature would enhance the versatility of the system
http://localhost/streamname.ts or something. I hope mpeg2/h262 supported

This is a legacy format that is used by less than 1% of live streams. Adding it wouldn't bring any benefit and increase the efforts to maintain the code.

> 2 SRT Publishing Without Stream Name It would be convenient if we could publish SRT streams without specifying a stream name just by using the format srt://ip:port Additionally it would be great if we could define custom ports for SRT playback for example srt://ip:customport These enhancements would make working with SRT more flexible
To add a section for predefined SRT streams with custom ports for publishing and playing in a mediamtx.yaml configuration file you can modify the YAML file as follows

This server works by opening a fixed number of ports, in order to allow users behind a NAT to map those ports and accept connections from outside the LAN. Opening a port for every single SRT stream would go against this design pattern, and would also limit the overall number of streams to 65536. Furthermore, allocating streams without an explicit configuration would not be possible anymore, since their port would be random and therefore impossible to determine without looking at the server logs.
