### ISSUE TITLE
Specify listening / capturing interface for UDP source

### ISSUE THREAD

**Issue by FlyveHest** [bluenviron/mediamtx#2533]
## Describe the feature
I am on a multi-interfaced host, and I am trying to setup an UDP source like this

```
  testudpa:
    source: udp://x.x.x.x:5500
```

But, mediamtx is not detecting the stream.

If I am using runOnDemand to grab the stream via ffmpeg, I have to specify the local interface the multicast streams are available on to get the stream working, like this

`ffmpeg -re -i udp://x.x.x.x:5500?localaddr=y.y.y.y`

It would be very nice to be able to specify either local IP or interface on an UDP source.

**Comment by aler9** [comment]
Hello, you didn't specify whether you want to pull a UDP stream from a unicast, broadcast or multicast address.

In case of unicast and broadcast addresses, specifying the local address is not necessary, since it's inferred automatically.

In case of multicast addresses, the server automatically listens for packets on all interfaces that support multicast, so specifying the local address should not be necessary too.

If you still have problems, open an issue and provide exact instructions on how to replicate them.

**Comment by FlyveHest** [comment]
It is from a multicast address.  I can see that mediamtx seems to detect a h264 stream, but I can't watch it on any endpoint, I just get a black screen in VLC.

Could it possibly be because the original stream contains multiple audio streams and EPG?

I won't be able to provide further information before next week, though.
