### ISSUE TITLE
RTSP source unauthorized starting with v1.1.0

### ISSUE THREAD

**Issue by bdariusb** [bluenviron/mediamtx#2545]
## Which version are you using?

v1.2.0

## Which operating system are you using?

Linux amd64 Docker

## Describe the issue

I started with version 1.2.0, tried proxying some rtsp streams from another instance of mediamtx, which worked fine. Afterwards I tried to proxy my rtsp ip camera streams and failed to do so with 401 coming from the ip camera server. Downgraded to version 1.1.0 and it didn't help, but with 1.0.3 it works, so I assume the bug appeared in 1.1.0. Seems like credentials are ignored??
The config: 
```
  ipc1:
    source: rtsp://xxx:yyy@192.168.1.160:554/1
    sourceProtocol: tcp
```

## Describe how to replicate the issue

1. start the docker container with version 1.1.0 or 1.2.0
2. set up rtsp source with basic auth in the uri

## Did you attach the server logs?

yes
debug log:
```
2023/10/22 18:18:43 INF MediaMTX v1.1.0
2023/10/22 18:18:43 DEB [path all_others] created
2023/10/22 18:18:43 DEB [path ipc1] created
2023/10/22 18:18:43 DEB path manager created
2023/10/22 18:18:43 INF [path ipc1] [RTSP source] started
2023/10/22 18:18:43 DEB [path ipc1] [RTSP source] connecting
2023/10/22 18:18:43 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/10/22 18:18:43 INF [RTMP] listener opened on :1935
2023/10/22 18:18:43 INF [HLS] listener opened on :8888
2023/10/22 18:18:43 INF [WebRTC] listener opened on :8889 (HTTP)
2023/10/22 18:18:43 INF [SRT] listener opened on :8890 (UDP)
2023/10/22 18:18:43 DEB [path ipc1] [RTSP source] [c->s] OPTIONS rtsp://192.168.1.160:554/1 RTSP/1.0
CSeq: 1
User-Agent: gortsplib


2023/10/22 18:18:43 DEB [path ipc1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: OPTIONS, DESCRIBE, SETUP, PLAY, PAUSE, TEARDOWN, SET_PARAMETER
Server: Rtsp Server


2023/10/22 18:18:43 DEB [path ipc1] [RTSP source] [c->s] DESCRIBE rtsp://192.168.1.160:554/1 RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: gortsplib


2023/10/22 18:18:43 DEB [path ipc1] [RTSP source] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 2
Server: Rtsp Server 720*480*25*4096
WWW-Authenticate: Digest realm="Surveillance Server", nonce="02102069"


2023/10/22 18:18:53 ERR [path ipc1] [RTSP source] request timed out
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, in order to fix this issue, we need a network dump, that can be generated in this way:

If the bug arises when using MediaMTX with an external hardware or software, the most helpful content you can provide is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by bdariusb** [comment]
I tried reproducing today, updated to latest docker image and... to no avail. It's working 🎉 Closing the issue
