### ISSUE TITLE
 invalid SDP: sdp: invalid numeric value `-8959200248001175080`

### ISSUE THREAD

**Issue by RomenKlaassen** [bluenviron/mediamtx#2708]
## Which version are you using?

v1.3.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When trying to connect to RTSP camera Y-CAM Bullet HD: 1080, I get the error 
 invalid SDP: sdp: invalid numeric value `-8959200248001175080` on startup.

## Describe how to replicate the issue

1. started the server with the following line in .yml:
  mycamera:
    source: rtsp://username:password@192.168.1.7:554/v01
    
## Did you attach the server logs?

**no**

## Did you attach a network dump?

**no**

**Comment by aler9** [comment]
Hello, this can be fixed but you need to attach a server log with the option `logLevel` set to `debug` in `mediamtx.yml` and then replicate the issue.

**Comment by lqbrqt** [comment]
Facing the same error with AXIS 221 camera. In the attachments there are logs from mediamtx with debug level
[mtxlog.txt](https://github.com/bluenviron/mediamtx/files/14997527/mtxlog.txt)

**Comment by aler9** [comment]
@lqbrqt thanks for providing the camera model and the log, please test the release attached in this page (click on Artifacts, binaries) and let me know if it fixes the issue:

https://github.com/bluenviron/mediamtx/actions/runs/8707155701

**Comment by lqbrqt** [comment]
@aler9 Thank you for really quick response! Currently, when running nightly build there is no output image from mediamtx (we're getting black screen), while using stable version image from 3 of 4 cameras are present. Also, in logs SDP error is not present. Sending you logs from provided mediamtx version [mtxnightlylog.log](https://github.com/bluenviron/mediamtx/files/15010776/mtxnightlylog.log)

**Comment by aler9** [comment]
@lqbrqt the problem you are describing is a different one that is not the subject of this issue.

If you are sure it's a bug then you need to open another issue and attach two network dumps, one that contains exchanged packets between a camera and VLC, and the other that contains exchanged packets between the server (proxying a camera) and VLC, in order to spot the differences. You can find instructions on how to generate network dumps when you try to open an issue.

**Comment by aler9** [comment]
Anyway, i'm noticing that the server is stripping the [MPEG4-IOD](https://mpeg.chiariglione.org/faq/whats-mpeg-4-initial-object-descriptor-iod) from the SDP of your cameras. This is the SDP that the camera provides:

```
v=0
o=- 1713376272799653 1713376272799661 IN IP4 192.168.221.101
s=Media Presentation
e=NONE
c=IN IP4 0.0.0.0
b=AS:8000
t=0 0
a=control:*
a=range:npt=now-
a=mpeg4-iod: "data:application/mpeg4-iod;base64,AoDUAE8BAf/1AQOAbwABQFBkYXRhOmFwcGxpY2F0aW9uL21wZWc0LW9kLWF1O2Jhc2U2NCxBUjBCR3dVZkF4Y0F5U1FBWlFRTklCRUVrK0FBZWhJQUFIb1NBQVlCQkE9PQQNAQUABAAAAAAAAAAAAAYJAQAAAAAAAAAAAzoAAkA2ZGF0YTphcHBsaWNhdGlvbi9tcGVnNC1iaWZzLWF1O2Jhc2U2NCx3QkFTWVFTSVVFVUZQd0E9BBICDQAAAgAAAAAAAAAABQMAAEAGCQEAAAAAAAAAAA=="
m=video 0 RTP/AVP 96
b=AS:8000
a=framerate:30.0
a=control:trackID=1
a=rtpmap:96 MP4V-ES/90000
a=fmtp:96 profile-level-id=245; config=000001B0F5000001B509000001000000012008D48D88032514043C14440F
a=mpeg4-esid:201
```

and this is the SDP that the server provides to any reader:

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=control:rtsp://127.0.0.1:8554/my_camera_fourth/trackID=0
a=rtpmap:96 MP4V-ES/90000
a=fmtp:96 config=000001B0F5000001B509000001000000012008D48D88032514043C14440F; profile-level-id=245
```

the `mpeg4-iod` attribute has gone lost. Maybe this is the cause. Open a dedicated issue in order to move discussion there.

**Comment by lqbrqt** [comment]
In addition to researching the reasons for the negative SDP number, it occurs when date/time is not synchronised correctly on the camera. To fix it - configure date and time in camera's settings
