### ISSUE TITLE
In-built Amazon Kinesis Video Streams support (KVS)

### ISSUE THREAD

**Issue by wryun** [bluenviron/mediamtx#2757]
## Describe the feature

It would be great if MediaMTX was able to send streams to KVS itself, possibly using https://github.com/seqsense/kinesisvideomanager/ (haven't actually tried to use this). I'm not sure how well it fits into MediaMTX's current configuration (based around sources), but I think it fits in with its broader objective of turning input streams into various output formats.

The reason I'm interested in using mediamtx for this is that we're running on devices with limited flash (32mb) and memory (128mb), so using the AWS provided gstreamer plugin (KVS) is considerable overhead, particularly if there are many streams.

Let me know if this would be a feature you'd consider, as some point I might look at adding it myself.

**Comment by aler9** [comment]
Hello, forwarding streams to external servers is perfectly possible through external software. Regarding Kinesis, i provided instructions here: https://github.com/bluenviron/mediamtx/issues/464#issuecomment-933597897

For the moment, i prefer not to develop native stream forwarding into the server, since this feature is already provided by external software and i need to minimize the maintenance effort.
