### ISSUE TITLE
After 6 hours I can't read the rtmp / srt streams

### ISSUE THREAD

**Issue by p4xx07** [bluenviron/mediamtx#2760]
## Which version are you using?

v1.3.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [x] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I stream for more than 6 hours playing the rtmp url of the stream becomes impossibile. And I can't understand why.

## Describe how to replicate the issue

1. start the server
2. publish with rtmp / srt
3. read with rtmp / srt
4. Use a software to read the stream (for example: ffplay/vlc for rtmp, mpv for srt)
5. After many hours the player stops playing and the stream seems to be unusable.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, please attach a network dump of traffic generated between the server and a player, when you try to read a stream from a player to the server AFTER the stream gets unusable. A network dump can be generated in this way:

If the bug arises when using MediaMTX with an external hardware or software, the most helpful content you can provide is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging packets (if the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by NacerFaraj** [comment]
I have the exact same problem! After a while, say for a few hours, player cannot get the published rtmp and rtsp streams.

**Comment by NacerFaraj** [comment]
I have the exact same problem! After a while, say for a few hours, player cannot get the published rtmp and rtsp streams.

**Comment by NacerFaraj** [comment]
> I have the exact same problem! After a while, say for a few hours, player cannot get the published rtmp and rtsp streams.

I am still facing this problem. When the number of cameras is less than 10, it is fine, but with a higher number of cameras, it refuses connection whenever any camera tries to establish a connection to publish.

**Comment by aler9** [comment]
closed since no useful information was provided to replicate the bug.
