### ISSUE TITLE
readBufferSize / readBufferCount no longer valid config options that fixed ([RTSP source] buffer length exceeds 64)

### ISSUE THREAD

**Issue by t3therdev** [bluenviron/mediamtx#2780]
## Which version are you using?

v1.3.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

For some RTSP cameras there was a previous fix to address the issues of [RTSP source] buffer length exceeds 64
These were readBufferSize & readBufferCount but they are no longer valid config options for RTSP.
Currently this does not allow us to use the cameras where this is a problem. 

## Describe how to replicate the issue

1. start the server
2. publish with RTSP Camera
3. read with ffplay or other
4. Log error shows buffer length exceeds 64

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, those options were removed because they are no longer necessary, the server is now able to receive packets of any size without tuning any parameter. Anyway, they didn't influence error "buffer length exceeds 64" in any way. If you still have problems, you need to generate and attach a network dump, that can be generated in this way:

1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by aler9** [comment]
closed since author did not provide requested data.
