### ISSUE TITLE
The video size of camera is not correct to 1920x1080

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#2845]
## Which version are you using?

v1.4.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The video size of camera is not correct to 1920x1080 when publishing with chrome of Android phone.

## Describe how to replicate the issue

1. start the server
2. publish with chrome of Android: https://192.168.10.10:8889/live/publish
3. set my phone to shoot in landscape mode
4. read with chrome of PC: http://127.0.0.1:8888/live
5. the video size of camera is not correct to 1920x1080
## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, after some research it was discovered that the framerate, width and height specified in the WebRTC publish page are not enforced, but used as reference. The actual width, height and framerate are picked from a set of fixed values, that depends on the specific camera, and are chosen to be as similar as possible to the reference ones. This is a WebRTC behavior that cannot be changed.

In order to avoid confusion i've renamed "video width" into "video width (ideal)" and so on (#3254).
