### ISSUE TITLE
Autel RTMP Streaming: not enough bits

### ISSUE THREAD

**Issue by lulu-py** [bluenviron/mediamtx#2938]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

In relation to the question 2829 (https://github.com/bluenviron/mediamtx/discussions/2829), when an autel drone streams in rtmp, the following error appears:

closed: not enough bits

## Describe how to replicate the issue

1. start the server
2. publish with Autel EVO II - Remote Controller V3
3. read with --

## Did you attach the server logs?

yes 

## Did you attach a network dump?

yes

[Autel-log_pcap.zip](http[Autel-log_pcap(1).zip](https://github.com/bluenviron/mediamtx/files/14392569/Autel-log_pcap.1.zip)

**Comment by aler9** [comment]
The dump you provided doesn't contain any valid RTMP packet, just acknowledges without any payload:

![Screenshot_20240419_231349](https://github.com/bluenviron/mediamtx/assets/46489434/e4755deb-240e-49bb-b7bd-8daa39249110)

Please provide another dump. The dump is needed in order to run a simulator that allows to replicate the bug. If the bug cannot be replicated, the issue cannot be solved.

**Comment by lulu-py** [comment]
The problem has been resolved with version 1.8.0 and an update to the altar application.
