### ISSUE TITLE
Playback API support for HEAD method

### ISSUE THREAD

**Issue by tbnguyen1407** [bluenviron/mediamtx#2943]
## Version

1.5.0

## Describe the feature

Currently there is no way to check if recording is available without actually downloading the file, which could be very big.

```
GET /get?path=...

## responses
200: ok (with mp4 in body)
404: no recording found
```

I suggest adding support for HEAD method for peeking without downloading

```
HEAD /get?path=...

## responses
200: ok (no body)
404: not found
```

Currently `HEAD` always return `404`, which probably means server does not have explicit support for it.

Thank you.

**Comment by eravellaSC** [comment]
I think you're describing pull request #2901. This could be a valid addition.

**Comment by aler9** [comment]
Hello, in order to find out whether a recording is available, there's the `/list` endpoint:

```
http://localhost:9996/list?path=[mypath]
```

that returns a JSON response that can be easily parsed:

```json
[
  {
    "start": "2006-01-02T15:04:05Z07:00",
    "duration": "60.0"
  },
  {
    "start": "2006-01-02T15:07:05Z07:00",
    "duration": "32.33"
  }
]
```

Although the suggestion of the HEAD method is extremely valid, i'd rather not add an additional feature that provides something that is already provided by another feature, would be used by few people and increase maintenance efforts.
