### ISSUE TITLE
runOnDemand command doesn't stop the processes executed from the win10 batch

### ISSUE THREAD

**Issue by rktr2009** [bluenviron/mediamtx#3004]
## Which version are you using?

v1.5.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

A batch file , which consist of a streamlink -> ffmpeg pipe as source to mediamtx, is successfully called at runOnDemand, but doesn't close the processes after the time of runOnDemandCloseAfter.

Setup is,
paths:
  stream1:
    runOnDemand: cmd /k "C:\Users\Applications\batch\stream1.bat"
    runOnDemandStartTimeout: 30s
    runOnDemandCloseAfter: 30s

Inside of stream1.bat is like,
streamlink https://www.youtube.com/watch?v=VNaaaaaaaa 360p -O | ffmpeg -re -i - -vcodec copy -acodec libmp3lame -r 5 -f rtsp rtsp://192.168.111.111:8554/

## Describe how to replicate the issue

Happens everytime I access the stream from the client. 
If mediamtx is terminated, the processes will terminate too.
It used to work before but started to fail to terminate the processes I think from the last version of rtsp-simple-server or around that. 

## Did you attach the server logs?

I see in the log,
runOnDemand command stopped: not needed by anyone,
but doesn't terminate the child processes.

## Did you attach a network dump?

no

**Comment by DigitalRogues** [comment]
I ran into this also with linux and having a bash script as the runondemand command, but once I moved all the code out of the script into the yaml directly it worked.

it would be nice to have the bash script get terminated as well.

**Comment by rktr2009** [comment]
> I ran into this also with linux and having a bash script as the runondemand command, but once I moved all the code out of the script into the yaml directly it worked.
> 
> it would be nice to have the bash script get terminated as well.

Great that worked for you, bringing the script into yaml :) I tried that before in windows, but somehow couldn't convert the script into yaml which gave me errors. The pipe part(updated above) didn't work I guess.

**Comment by aler9** [comment]
Hello, after replicating the issue on both Linux and Windows, it turned out that MediaMTX does indeed send the kill signal to the process written inside `runOnDemand`, but not to its subprocesses, if there are any, causing them to remain active.

In case of commands wrapped inside shell scripts like `cmd /k "C:\Users\Applications\batch\stream1.bat"`, the main process is `cmd.exe` and not `streamlink.exe` or `ffmpeg.exe`.

In order to ease the integration with third-party software, i wrote a patch that propagates the kill signal to subprocesses too, and this should solve the issue on all supported operating systems.

Contrarily to what reported in this thread, closing subprocesses was never a feature of rtsp-simple-server.

**Comment by rktr2009** [comment]
After testing, I am not really sure if runOnDemandCloseAfter is kicking in exactly after 30s, as per my config, but I can see the processes are closing around that timeframe, thanks!
