### ISSUE TITLE
Hls m3u8 file should be also created and updated in same directory when is ts files created in hlsDirectory.

### ISSUE THREAD

**Issue by EvgIL74** [bluenviron/mediamtx#3095]
## Which version are you using?

v1.5.1

## Which operating system are you using?

Linux amd64 standard

## Describe the issue

Hls m3u8 file should be also created and updated in same directory when is ts files created in hlsDirectory.

## Describe how to replicate the issue

1. start the server
2. publish with srt/rtmp 
3. look at hls directory and no m3u8 on disk.

## Did you attach the server logs?

no

## Did you attach a network dump?
 no

**Comment by aler9** [comment]
Hello, this won't be developed. The `hlsDirectory` parameter was conceived to offload segments from RAM, not create a folder that can be served with an external HTTP server. An external HTTP server is not capable of serving an HLS low-latency stream, since it misses the ability to provide [blocking playlists](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-6.2.5.2) and (preload hints)[https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-6.2.6]).

If you want to scale, you can use a CDN in front of the server, as mentioned in the README.

If you want to store segments, use the record feature.
