### ISSUE TITLE
RunOnInit

### ISSUE THREAD

**Issue by dlucas9** [bluenviron/mediamtx#3214]
## Which version are you using?

v1.6.0

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ x] Linux arm64 standard
- [ x] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RunOnInit complains with
"ERR: a path with a regular expression (or path 'all') does not support option 'runOnInit'; use another path"

## Describe how to replicate the issue

Set a command for RunOnInit as described in the README and run mediamtx.

## Did you attach the server logs?

NO

## Did you attach a network dump?

NO

**Comment by eravellaSC** [comment]
Did you set the `RunOnInit` for all path? You can't do that, as the error suggests.

**Comment by aler9** [comment]
Hello, `runOnInit` is meant to be moved inside the `paths` section, in this way:

```yml
paths:
  mypath:
    runOnInit: mycommand
```

The documentation is definitely not clear, this is because all path parameters were recently moved to `pathDefaults`, which is a new variable that allows to set default values for all paths. There are some variables that cannot be set automatically on all paths but must be set on explicit paths. We'll see what we can do about it in the future.
