### ISSUE TITLE
ERR [record] too many reordered frames (11)

### ISSUE THREAD

**Issue by QuangLinh2000** [bluenviron/mediamtx#3315]
## Which version are you using?

v1.8.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I store video from a rtsp stream of Tiandy camera series with a duration of 5 minutes, but its recording is interrupted into files smaller than 5 minutes and it gives an error  ERR [record] too many reordered frames (11)
![image](https://github.com/bluenviron/mediamtx/assets/91469087/2823baaa-cba2-47a2-8fed-328833cd71fe)
- Camera configuration
![image](https://github.com/bluenviron/mediamtx/assets/91469087/2ae151f9-9666-4350-92ce-ab9221506d79)

## Describe how to replicate the issue

1. Config server
![image](https://github.com/bluenviron/mediamtx/assets/91469087/b6ab3e94-b845-4b89-acda-0ca37c9fbe00)
![image](https://github.com/bluenviron/mediamtx/assets/91469087/c20e0ded-0980-4325-9349-f548ec1cc4a1)

2.start the server

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, in order to solve this bug we need a network dump, that can be generated in this way:

If the bug arises when using MediaMTX with an external hardware or software, the most helpful content you can provide is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging packets (if the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by moenodedev** [comment]
Could be related to #3091

**Comment by aler9** [comment]
closed since required data was not provided.
