### ISSUE TITLE
Accept German Characters in Camera Path Validation

### ISSUE THREAD

**Issue by MahmoudHassan77** [bluenviron/mediamtx#3413]
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [X] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The current implementation of the camera path validation regex does not accept German characters. This feature request is to enhance the regex pattern to support German characters (ä, ö, ü, Ä, Ö, Ü, ß).

Additionally, mediamtx can't read RTMP streams, resulting in the error [RTMP source] not enough bytes. This stream works fine with other RTMP clients (VLC, OBS, vMix, etc.).

Proposed Change:
Modify the regex pattern in the line:
var rePathName = regexp.MustCompile(^[0-9a-zA-Z_-/.~]+$)

to include German characters. The updated regex should look like this:
var rePathName = regexp.MustCompile(^[0-9a-zA-Z_-/.~äöüÄÖÜß]+$)

## Describe how to replicate the issue

Locate the line with the current regex pattern:
var rePathName = regexp.MustCompile(^[0-9a-zA-Z_-/.~]+$)
Update it to include German characters:
var rePathName = regexp.MustCompile(^[0-9a-zA-Z_-/.~äöüÄÖÜß]+$)
Test the validation to ensure it now accepts paths with German characters.

## Did you attach the server logs?

invalid path name: can contain only alphanumeric characters, underscore, dot, tilde, minus or slash (I2_Kühlthekßä_4_Non_food)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, unfortunately we cannot implement this since there's an high risk of causing compatibility issues with some clients, that might be using character encodings different than UTF-8.  In particular, in Germany there's still an high percentage of users that are using [ISO 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), making impossible to transmit German characters correctly between different machines (without first declaring the encoding, which is something that a web page does, but RTSP does not).
