### ISSUE TITLE
Adding GELF logging protocol for logDestinations

### ISSUE THREAD

**Issue by Creepios** [bluenviron/mediamtx#3429]
## Describe the feature

Implement the feature, that you can publish log ("logDestinations") with GELF protocol (Graylog Extended Log Format) to a remote log server.
https://go2docs.graylog.org/current/getting_in_log_data/gelf.html
In my opinion, it would be very useful that you can live analyze logs in a very clearly arranged software like Graylog, especially when you have multiple mediamtx application running at the same time.

**Comment by Creepios** [comment]
Alternative would be that you can publish it also with remote syslog protocol

**Comment by aler9** [comment]
Hello,
Graylog already supports ingesting MediaMTX logs through systemd. The GELF format would be an improvement since it allows to pass structured data in place of plain strings. We are currently not generating structured data, but if we do it in the future, we would probably use the [fluentd protocol](https://docs.fluentd.org/input/udp) since fluentd is released under a a [more permissive license](https://github.com/fluent/fluentd?tab=Apache-2.0-1-ov-file#readme) than [Graylog's](https://github.com/Graylog2/graylog2-server?tab=License-1-ov-file#readme).
