### ISSUE TITLE
[RTSP source] [c->s] TEARDOWN

### ISSUE THREAD

**Issue by Cramac** [bluenviron/mediamtx#3434]
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Constantly disconnects from the stream. I don't understand why. If you watch the stream through VLC, there are no problems. Zoneminder also keeps the connection stable

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...
[mediamtx.yml.txt](https://github.com/user-attachments/files/15744409/mediamtx.yml.txt)

## Did you attach the server logs?

yes 
[mediamtx.log](https://github.com/user-attachments/files/15744417/mediamtx.log)

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Hello, from the logs you posted it seems like the TEARDOWN is caused by a timeout when reading RTP packets from the camera:

```
2024/06/07 21:26:03 DEB [path domofon_89] [RTSP source] [c->s] TEARDOWN rtsp://172.20.20.160/av0_1 RTSP/1.0
Authorization: Digest username="admin", realm="BWD Streaming", nonce="bdca69c73f4f834bb3e2cd84bc901146", uri="rtsp://172.20.20.160/av0_1", response="10db8ff8785ffe7c40f4b046fe05a818"
CSeq: 12
Session: 4949421130333060406
User-Agent: gortsplib
2024/06/07 21:26:03 ERR [path domofon_89] [RTSP source] TCP timeout
```

In order to find out why this timeout is triggered, we need a network dump of communications between the server and the camera, that can be generated in this way:

1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging packets (if the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by Cramac** [comment]
[dump.zip](https://github.com/user-attachments/files/16119502/dump.zip)

**Comment by aler9** [comment]
The reason for this issue is that in the configuration you set timeouts to extremely low values:

```
readTimeout: 1s
writeTimeout: 1s
```

In RTSP, video frames are splitted in multiple RTP packets. When RTP packets are transmitted through TCP, they can be splitted further. When MediaMTX receives a FULL RTP packet, current timestamp is stored inside a variable:

https://github.com/bluenviron/gortsplib/blob/690c0b002231fd499e0e0ba0ffa6d69adf9105a8/client_media.go#L191-L193

Then there's a periodic routine that checks the timestamp of the last RTP packet against the current timestamp, triggering a timeout error:

https://github.com/bluenviron/gortsplib/blob/690c0b002231fd499e0e0ba0ffa6d69adf9105a8/client.go#L1002-L1004

Some RTP packets may require more than 1 second to be fully transmitted, especially when they contain full video frames.

Increase the timeout values to at least `5s`.
