### ISSUE TITLE
OBS 30.2 Beta 1 - NVENC HEVC encoder fails with mediamtx whip server

### ISSUE THREAD

**Issue by Fxzzi** [bluenviron/mediamtx#3435]
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

NVENC HEVC encoder fails with mediamtx whip server. Continual disconnect and reconnect to the server as shown by OBS notifications: 
![image](https://github.com/bluenviron/mediamtx/assets/18248986/cf217e77-fafa-4686-b787-5dd51bdb5fc0)

## Describe how to replicate the issue

1. Use OBS beta
2. Set streaming settings to mediamtx server
3. Ensure video encoder is nvenc hevc
4. attempt to stream and notice failures to stream

## Did you attach the server logs?

yes: [mediamtx.log](https://github.com/user-attachments/files/15747639/mediamtx.log)

## Did you attach a network dump?

no

OBS discord notified me that this looks like a mediamtx issue. They advised I send you the OBS debug log too. Here you go: [obs-verbose.log](https://github.com/user-attachments/files/15747642/obs-verbose.log)

**Comment by aler9** [comment]
Hello, as clearly mentioned in the README we don't support using H265 with WebRTC, mainly because the great majority of browsers do not support it.

The OBS team decided to unlock the WebRTC-H265 combination last month (see https://github.com/obsproject/obs-studio/pull/10577) , therefore we can add support for ingesting H265 streams with WebRTC, but not for reading them from the server.
