### ISSUE TITLE
Modified to send Ctrl+C signal instead of closeHandle

### ISSUE THREAD

**Issue by leadtech-jwyun** [bluenviron/mediamtx#3453]
## Describe the feature

Description
I understand that if it is executed with runOnDemand, it is later terminated with closeHadle on Windows.

In this case, the program terminates unsafely.

So, send the ctrl+c signal so that the program can be terminated safely.

**Comment by aler9** [comment]
Hello, this is not possible since in order to terminate custom commands on Windows we're using the [JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_basic_limit_information) flag that "causes all processes associated with the job to terminate when the last handle to the job is closed". There are no other available flags that allow to send a less strict signal.

If you want more control over a custom command, you can use `runOnUndemand` or switch to Linux, which has a broader range of signals.
