### ISSUE TITLE
mp4 playback can not play while buffering

### ISSUE THREAD

**Issue by shitizenlism** [bluenviron/mediamtx#3565]
## Which version are you using?
v1.8.2

## Which operating system are you using?
- [x] Linux amd64 standard
ubuntu 22.04

## Describe the issue
browser can not play till mp4 file downloaded. 
example vod: https://s.warkdsa.com/recordings/8201389_Main-1264837662334880832665.mp4

## Describe how to replicate the issue
record a xxx.mp4 file and upload to aws s3 storage and playback.
or just use nginx to playback. mp4 can not play until mp4 downloaded.
I will check if v1.8.4 fixed this issue. 

## Did you attach the server logs?
no. I will provide if necessary.

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Hello, the server generate recordings in FMP4 format, which can be played by most browsers without waiting for the download to complete. You didn't write browser name or version, therefore no further help can be provided.

If the FMP4 format is causing compatibility issues, try downloading standard MP4 files through the Playback server, instead of using MP4 files stored on disk, as mentioned in the README:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#playback-recorded-streams)
