### ISSUE TITLE
Does MediaMTX support WebSocket as an input source?

### ISSUE THREAD

**Issue by Martayugui** [bluenviron/mediamtx#3723]
## Describe the feature

I am exploring the possibility of using MediaMTX to handle video streams coming from a WebSocket source:

- Does MediaMTX currently support WebSocket as an input protocol?
- If not, are there any plans to add this feature in the future?
- Are there any recommended workarounds or alternative approaches to get a WebSocket stream into MediaMTX?

I am particularly interested in this because the incoming video frames are larger than the UDP maximum size packets (64KB)

Thank you for any information or guidance you can provide!

**Comment by aler9** [comment]
Hello, we don't support this since WebSocket by itself is not a video streaming protocol but a generic transport for exchanging byte-based packets.
If you have video frames larger than the UDP maximum size, it's enough to mux them into RTP packets, splitting them into several small packets that are then re-assembled at server side.
