### ISSUE TITLE
Hooks don't work

### ISSUE THREAD

**Issue by paullaffitte** [bluenviron/mediamtx#3733]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Most of the time, hooks just don't work, using WebRTC or HLS. I defined all hooks, and when I open a stream and play with HLS it never ever trigger any hook, and with WebRTC it ionly trigger `OnRead` and `OnUnread`, and `OnUnread` it triggered even while the stream is playing.

## Describe how to replicate the issue

1. Configure all hooks
2. Start the server
3. Stream using HLS and/or WebRTC

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by aler9** [comment]
Hello,
Regarding HLS, this is expected since in HLS there's no concept of reader - see #962
Regarding WebRTC, the question is not clear since you didn't attach server logs and therefore it's impossible to understand if and how the possible duplication of onUnread happens.
If you have further issues, open another bug report with required data.
