### ISSUE TITLE
webrtc read does not work on desktop / mobile safari

### ISSUE THREAD

**Issue by ransomhmc** [bluenviron/mediamtx#3917]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

1. start the server,
2. publish webrtc stream via browser: https://MY_SERVER/webrtc/publish
    - using all default settings, only change video codec from AV1 to VP8
4. read with chrome for MacOS at https://MY_SERVER/webrtc: OK
5. read with safari for MacOS: NG, stream does not start
6. read with safari for iOS: NG, stream does not start

**Comment by esonti** [comment]
I face the same issue too. 

My setup is using mediamtx 1.9.4  installed on a Pi with Pi HQ Camera. 

Webrtc stream is diplayed as expected on windows/linux in Edge, chrome browsers. Only on ios and mac on safari browsers it doesnt display anything.

**Comment by aler9** [comment]
@ransomhmc i tested publishing a WebRTC stream through Chrome 129, using the VP8 codec and i was able to read it with WebRTC through both macOS Safari and iOS Safari. If the issue still persists, open another bug report and provide server logs with `logLevel: debug`, the name and version of the browser you are using to publish the stream and the name and version of browsers you are using for reading the stream, as written in the bug report instructions.

@esonti your issue is completely unrelated from this one.
