### ISSUE TITLE
Add support for query parameters in the RTSP path within the configuration file

### ISSUE THREAD

**Issue by tri-umbo** [bluenviron/mediamtx#3929]
### Which version are you using?
v1.9.3

### Feature Request
At present, mediamtx supports query parameters for RTSP paths only when they are defined outside of the configuration file (mediamtx.yml). Attempting to add an RTSP path with a query parameter in the configuration file results in an error:
`ERR: invalid path name 'Streaming/Channels/102?transportmode=unicast&profile=Profile_3': can contain only alphanumeric characters, underscore, dot, tilde, minus or slash`. 
Could support for query parameters be added to the path field within the configuration file as well?

**Comment by aler9** [comment]
Hello, if what you want is specifying both path name and query parameters in this way:

```yml
paths:
  'mypath/Streaming/Channels/102?transportmode=unicast&profile=Profile_3':
    source: mysource
```

This is technically possible to implement but i don't think it's a good idea to do that - the entire server is built on the concept of using path names as keys, furthermore query parameters are often used to propagate dynamic and sensitive data (credentials) through reverse proxies and identity servers, and binding them to specific values would cause troubles to the vast majority of users.

However, it seems to me that your aim is simulating a HikVision camera, therefore my advice is to use [gortsplib](https://github.com/bluenviron/gortsplib) rather than MediaMTX and build a custom RTSP server that checks for path name and query parameters and act accordingly.

A server example is here:
https://github.com/bluenviron/gortsplib/blob/main/examples/server/main.go

A proxy example is here:
https://github.com/bluenviron/gortsplib/blob/main/examples/proxy/main.go
