### ISSUE TITLE
Support embedding mediamtx in other Go binaries

### ISSUE THREAD

**Issue by iameli** [bluenviron/mediamtx#4011]
### Describe the feature

Hi! I'm working on a video project that, for various reasons, is required to ship as a single statically-linked Go binary. I'd love to use MediaMTX (by forking and calling `core.New`) but as things currently stand I'd have to package up MediaMTX adjacent to my binary. As far as I can tell, there are only two things standing in the way of this being possible:

1. All of MediaMTX's code is in an `internal` subdirectory. I assume that means at some point somebody thought it was a bad idea to support MediaMTX in other Go binaries, so we can have a discussion about that.
2. There's a `go generate` step to create a VERSION file and download HLS.js and mediamtx-rpicamera. There probably exist workarounds for this, such as running this step as part of the process of publishing new package versions and including them in the tagged releases.

Would love to hear your thoughts!

**Comment by aler9** [comment]
Hello,

> All of MediaMTX's code is in an internal subdirectory. I assume that means at some point somebody thought it was a bad idea to support MediaMTX in other Go binaries, so we can have a discussion about that.

This was already discussed in #533. We won't expose a public interface since that would mean guaranteeing its backward compatibility. Just fork the server and move what you need into the `pkg` folder.

> There's a go generate step to create a VERSION file and download HLS.js and mediamtx-rpicamera. There probably exist workarounds for this, such as running this step as part of the process of publishing new package versions and including them in the tagged releases.

We need to run a pre-compilation process as lots of project do. While some compilers allow to define pre-processing stages that are executed automatically (like Meson and Maven), the Go compiler requires a manual command, that is `go generate`, that has to be run before `go build`. Running it does not influence the ability to embed the server into another executable (after you have moved what you need into the `pkg` folder).
