### ISSUE TITLE
Clock time recording segments

### ISSUE THREAD

**Issue by libexpand** [bluenviron/mediamtx#4057]
### Describe the feature

Add support for splitting recordings into segments aligned with clock time intervals (similar to FFmpeg's `segment_atclocktime`).

The time value specified is used for setting the length of the splitting interval. For example a value of "15m" makes it possible to record segments at 12:00 o’clock, 12:15, 12:30, etc.

**Comment by Drengel1990** [comment]
This is the recordSegmentDuration parameter, but it stopped working in new releases

**Comment by aler9** [comment]
Hello, recording segments cannot be cut at will since videos can only be cut in the presence of an I-frame, furthermore they are not designed for direct usage but for resilience in case of crashes.

The component in charge of converting recording segments into something that can be served is the [playback server](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#playback-recorded-streams), which already allows to generate video fragments that starts from a desired instant and have a desired length:

http://localhost:9996/get?path=mypath&start=2024-01-14T16%3A00%3A17%2B00%3A00&duration=300

**Comment by aler9** [comment]
mpv and any other player fully support reading segments from the playback server through HTTP calls.

Every time you are restarting the recording system you are losing some seconds of recording since, as I mentioned before, segments can be created only in presence of an I frame, which usually happens after some seconds.

The playback server can generate segments that starts at precise instants, eventually including I frames from the past if needed, without interfering with the recording process.
