### ISSUE TITLE
Reduce latency with WebRTC?

### ISSUE THREAD

**Issue by drunkinlove** [bluenviron/mediamtx#4063]
### Which version are you using?

1.10.0

### Which operating system are you using?

macOS amd64 Docker

### Describe how to replicate the issue

Hi! I'm trying to replace Parsec with WebRTC streaming using MediaMTX. I stream from one MacBook to another using the following setup:

1. Connect the laptops via Thunderbolt Bridge (should be very fast) 
2. Run the MediaMTX container on the client with default settings
3. Publish the stream on host using OBS:
- native videotoolbox HEVC encoder
- 5000kbps
- keyframe every 1s
- no bframes
- WHIP endpoint with client's Thunderbolt Bridge IP
4. Read on client using Safari at http://localhost:8889/mystream/publish

Overall it works very well, but I get around 100-200 ms latency, compared to 25 ms using Parsec on Wi-Fi. Are there any obvious ways I can reduce latency? Like replacing OBS or Safari, or running MediaMTX without Docker?

**Comment by aler9** [comment]
Hello, decreasing latency below 100ms is an interesting topic but i think you're dealing into an intrinsic limitation of the video streaming stack you want to use (browser-based WebRTC) - basically, latency is introduced by browsers in order to increase robustness in case of network fluctuations. They choose the latency value autonomously and adjust it according to measured speed.

Recently, a new browser-side option has been added in Chrome in order to provide a latency "hint" - as the name suggests, it's only a hint, that browsers might or might not decide to apply. For more details:
https://discourse.wicg.io/t/hint-attribute-in-webrtc-to-influence-underlying-audio-video-buffering/4038/

Parsec ships its own app, thus the video streaming part does not pass through common browsers.

In the future we will surely add to MediaMTX an additional transport based on WebCodecs, which do not have this limitation.

**Comment by drunkinlove** [comment]
Thanks! I'm new to video streaming, I suppose the browser delay was a given. Do you happen to know any other clients that can consume a WebRTC stream? The readme says:

> Known clients that can publish with WebRTC and WHIP are [FFmpeg](https://github.com/bluenviron/mediamtx/issues/4063#ffmpeg), [GStreamer](https://github.com/bluenviron/mediamtx/issues/4063#gstreamer), [OBS Studio](https://github.com/bluenviron/mediamtx/issues/4063#obs-studio), [Unity](https://github.com/bluenviron/mediamtx/issues/4063#unity) and [Web browsers](https://github.com/bluenviron/mediamtx/issues/4063#web-browsers).

...and this is where I get confused. They are called clients, but AFAIK ffmpeg and OBS can't _consume_ a WebRTC stream (though they can _publish_ one).

Also, do you happen to know any solutions for sending raw video over network? Sorry if this is out of the scope.

**Comment by aler9** [comment]
> and this is where I get confused. They are called clients, but AFAIK ffmpeg and OBS can't consume a WebRTC stream (though they can publish one).

Both publishers and readers are "client" of a media server. The readme also contains a list of clients that can read / consume a WebRTC stream. Furthermore, in MediaMTX conversion between protocols is automatic, so you can read a stream originally publish with WebRTC with any other protocol (currently RTSP, RTMP, SRT, HLS).

> Also, do you happen to know any solutions for sending raw video over network?

I don't advice you to do so since a single 1080p stream at 30fps requires 1920 * 1080 * 3 * 30 * 8 = 1.49 Gbps of bandwidth.
