### ISSUE TITLE
Usage as library

### ISSUE THREAD

**Issue by ItalyPaleAle** [bluenviron/mediamtx#533]
Would it be possible to use this server as a library inside another Go application?

I need to build an app (written in Go) that needs to spin up and destroy these servers on-demand (on a given port). Rather than forking new processes every time (inefficient), it would be much better for me to use this as a library. Right now, it doesn't seem possible as every package is in the "internal" folder.

**Comment by connormckelvey** [comment]
Came here to post the same thing. Would be awesome to have at least the high-level constructs available in a public `pkg` directory. I'm very interested in embedding this in another go application. Programmatic config changing and reloading would be great as well.

**Comment by aler9** [comment]
Hello, the server is already built on a [Golang RTSP library](https://github.com/aler9/gortsplib) that allows to build servers, are you sure you need to embed rtsp-simple-server instead of the library?

**Comment by aler9** [comment]
Since this topic was created, the server has been improved with a full-featured HTTP API that allows to perform programmatic config changes, reloads, queries about anything stored inside the server. Thus, the server can be embedded into another software in at least two ways:

* start the server as a child process and control it through the HTTP API
* if you're interested in a specific protocol, use one of the server components, like [gortsplib](https://github.com/bluenviron/gortsplib) and [gohlslib](https://github.com/bluenviron/gohlslib)

We won't add support for exposing internals components and using them in Go since this method would have a limited user base, would have a limited power with respect to the HTTP API and we cannot guarantee its backward compatibility.

If you really want to start the server through Go, without passing through a subprocess, fork the repo and move what you want into the `pkg` folder.
